name: gmic custom build

on: workflow_dispatch

jobs:
  build-gmic:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Run Docker
      run: |
        cd gmic
        mkdir artifact
        docker run
        
    - name: SSH
      id: ssh
      uses: mxschmitt/action-tmate@v3
    
    
    - name: Upload
      uses: actions/upload-artifact@v2
      with: 
        path: gmic/artifact
        name: gmic_build
